---
--- Created by echo.
--- DateTime: 2025/12/29 15:24
---
---@class CS.LuaRenderItem
---@field public eid number
---@field public posX number
---@field public posY number
---@field public posZ number
---@field public velocityX number
---@field public sheet string
---@field public spriteKey string
---@overload fun(): CS.LuaRenderItem
CS.LuaRenderItem = {}
