using System.Collections.Generic;
using UnityEngine;

namespace ConfigHandler
{
    /// <summary>
    /// Character Registry - ScriptableObject
    ///
    /// Holds references to all CharacterDefinition assets in the project.
    /// Provides fast lookup of Sprite by characterId.
    ///
    /// UI layer calls GetDefinition to attach Sprites to CharacterDef cards
    /// already generated by the JSON layer.
    /// Initialized at runtime by CharacterRegistryLoader (no global static Resources.Load).
    /// </summary>
    [CreateAssetMenu(
        fileName = "CharacterRegistry",
        menuName  = "Game/Character/Character Registry",
        order     = 11)]
    public class CharacterRegistry : ScriptableObject
    {
        [SerializeField]
        private List<CharacterDefinition> _definitions = new List<CharacterDefinition>();

        // Runtime lookup table, built after Initialize() ─────────────────────
        private Dictionary<string, CharacterDefinition> _lookup;

        /// <summary>
        /// Must be called once before use (triggered by CharacterRegistryLoader in Awake).
        /// </summary>
        public void Initialize()
        {
            _lookup = new Dictionary<string, CharacterDefinition>(_definitions.Count);
            foreach (var def in _definitions)
            {
                if (def == null) continue;
                if (string.IsNullOrEmpty(def.characterId))
                {
                    Debug.LogWarning($"[CharacterRegistry] '{def.name}' has empty characterId, skipped");
                    continue;
                }
                if (_lookup.ContainsKey(def.characterId))
                {
                    Debug.LogWarning($"[CharacterRegistry] Duplicate characterId '{def.characterId}', skipped '{def.name}'");
                    continue;
                }
                _lookup[def.characterId] = def;
            }
            Debug.Log($"[CharacterRegistry] Initialized with {_lookup.Count} character definition(s)");
        }

        /// <summary>
        /// Find a Definition by characterId; returns null if not found.
        /// </summary>
        public CharacterDefinition GetDefinition(string characterId)
        {
            if (_lookup == null)
            {
                Debug.LogError("[CharacterRegistry] Not initialized yet. Call Initialize() first.");
                return null;
            }
            _lookup.TryGetValue(characterId, out var result);
            return result;
        }

        /// <summary>Returns all registered definitions in order (read-only).</summary>
        public IReadOnlyList<CharacterDefinition> All => _definitions;
    }
}